### ISSUE TITLE
15(tag) game

### ISSUE THREAD

**Issue by SnikersFar** [JinOptimist/NET12#294]
Sometimes generator realized  not passable level
![image](https://user-images.githubusercontent.com/86854997/152633441-c37914c2-ac93-49aa-99a7-da476e19575e.png)

**Comment by SnikersFar** [comment]
@Anastasia1Minsk

**Comment by Anastasia1Minsk** [comment]
Thanks for testing @SnikersFar 
I wonder if this combination was made by random or by you
